# Generated by Django 4.2.9 on 2026-04-11 04:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
