# Generated by Django 4.2.9 on 2026-04-11 07:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_event_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="poster_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
